//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4Microformats.Calendar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResCalendar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResCalendar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC4Microformats.Calendar.ResCalendar", typeof(ResCalendar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&apos;vevent&apos;&gt;
        ///
        ///&lt;h3 class=&apos;summary&apos;&gt;{Summary}&lt;/h3&gt;
        ///
        ///&lt;p class=&apos;description&apos;&gt;{Description}&lt;/p&gt;
        ///&lt;p&gt;To be held on 
        /// &lt;span class=&apos;dtstart&apos;&gt;
        ///  &lt;abbr class=&apos;value&apos; title=&apos;DtStart:yyyy-MM-dd&apos;&gt;the {DtStart:dd MMMM yyyy}&lt;/abbr&gt; 
        ///  from &lt;span class=&apos;value&apos;&gt;{DtStart:HH:mm}&lt;/span&gt; 
        /// &lt;/span&gt; until 
        /// &lt;span class=&apos;dtlast&apos;&gt;
        ///  &lt;span class=&apos;value&apos;&gt;{DtEnd:HH:mm}&lt;/span&gt; 
        /// &lt;/span&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;&lt;a class=&apos;url&apos; href=&apos;{Url}&apos; target=&apos;_blank&apos;&gt;&lt;span class=&apos;location&apos;&gt; Location: {Location}&lt;/span&gt;&lt;/a&gt;
        /// &lt;/p&gt;&lt;/div&gt;.
        /// </summary>
        internal static string eFormatHTML {
            get {
                return ResourceManager.GetString("eFormatHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;article itemprop=&apos;vevent&apos; id=&apos;eventhtml5&apos; itemtype=&apos;http://microformats.org/profile/hcalendar&apos;&gt;
        ///&lt;h3 itemprop=&apos;summary&apos;&gt;{Summary}&lt;/h3&gt;
        ///&lt;p&gt;
        ///&lt;strong&gt;When:&lt;/strong&gt; &lt;data itemprop=&apos;dtstart&apos; value=&apos;{DtStart:yyyy-MM-dd}&apos;&gt;{DtStart:MMMM dd,yyyy}&lt;/data&gt; from &lt;data value=&apos;{DtStart:s}&apos; itemprop=&apos;dtstart&apos;&gt;{DtStart:HH:mm}&lt;/data&gt; until &lt;data value=&apos;{DtEnd:s}&apos; itemprop=&apos;dtend&apos;&gt;{DtEnd:HH:mm}&lt;/data&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///&lt;strong&gt;Where:&lt;/strong&gt; &lt;a class=&apos;url&apos; href=&apos;{Url}&apos; target=&apos;_blank&apos;&gt;&lt;span itemprop=&apos;location&apos;&gt;{Location}&lt;/span [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eFormatHTML5 {
            get {
                return ResourceManager.GetString("eFormatHTML5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div  itemscope=&apos;&apos; itemtype=&apos;http://schema.org/Event&apos;&gt;     
        ///      {Description}
        ///      &lt;span itemprop=&apos;name&apos;&gt; {Summary} &lt;/span&gt;
        ///     
        ///      &lt;meta itemprop=&apos;startDate&apos; content=&apos;{DtStart:s}&apos;&gt;
        ///        {DtStart:MMMM dd,yyyy}
        ///        &lt;/meta&gt;
        ///      &lt;div itemprop=&apos;location&apos; itemscope=&apos;&apos; itemtype=&apos;http://schema.org/Place&apos;&gt;
        ///        &lt;a itemprop=&apos;url&apos; href=&apos;{Url}&apos;&gt;
        ///       {Location}
        ///        &lt;/a&gt;
        ///      &lt;/div&gt;
        ///    &lt;/div&gt;.
        /// </summary>
        internal static string eFormatSchemaOrg {
            get {
                return ResourceManager.GetString("eFormatSchemaOrg", resourceCulture);
            }
        }
    }
}
